[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
via_ir = false
optimizer = true
optimizer_runs = 100
ffi=true
evm_version = "cancun"



[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
mantle_testnet = "https://rpc.testnet.mantle.xyz"